server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: "127.0.0.1:29092"
    admin:
      bootstrap-servers: "127.0.0.1:29092"
      auto-create: true
    producer:
      acks: all
      client-id: producer-app
